### ISSUE TITLE
node and edge handle string input differently

### ISSUE THREAD

**Issue by hodgett** [xflr6/graphviz#100] opened 2020-06-10 07:04 UTC
If I pass the string n1 = "http://brick.oclc.com.au:81/" to node `g.node(n1)` then it appears in the .gv file as "http://brick.oclc.com.au:81/". When I pass the same string to edge `g.edge(n1,n2)` it appears in the .gv file as http:"//brick.oclc.com.au":81/ which causes an error;
`syntax error in line 3001 near '/'`
The quotation marks get messed up. Why do the two functions handle the same string differently?

**Comment by xflr6** [comment] 2020-06-10 08:37
The [edge method](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Graph.edge) currently accepts `:`-separated strings as `node_id`s ([DOT language](https://www.graphviz.org/doc/info/lang.html)), currently splitting them naively into `node`, `port`, and `compass` (underdocumented unfortunately). AFAIU the DOT language principally allows `port` and `compass` also in node statements but they seem to be ignored, which is why the [node method](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.Graph.node) is different here.

The best current workaround is probably to use node names and labels where the wanted labels could contain colons:

```python
In [1]: import graphviz
   ...: 
   ...: g = graphviz.Graph()
   ...: g.node('A', 'http://brick.oclc.com.au:81/')
   ...: g.node('B', 'spam')
   ...: g.edge('A', 'B')
   ...: g
```
![graph](https://user-images.githubusercontent.com/6342379/84245791-e1d15500-ab05-11ea-9d68-1837f49633b1.png)

Duplicate of #53 (see discussion there).

**Closed by xflr6** 2020-06-10 08:37 UTC
