### ISSUE TITLE
my result of fdpclust.py  is different from the example

### ISSUE THREAD

**Issue by Rubiscooo** [xflr6/graphviz#98] opened 2020-04-24 04:35 UTC
![捕获](https://user-images.githubusercontent.com/49872316/80175208-8ca9b480-8627-11ea-824c-698f429a7269.PNG)

```python
from graphviz import Graph

g = Graph('G', filename='fdpclust.gv', engine='fdp')

g.node('e')

with g.subgraph(name='clusterA') as a:
    a.edge('a', 'b')
    with a.subgraph(name='clusterC') as c:
        c.edge('C', 'D')

with g.subgraph(name='clusterB') as b:
    b.edge('d', 'f')

g.edge('d', 'D')
g.edge('e', 'clusterB')
g.edge('clusterC', 'clusterB')

g.view()
```

why the edge g.edge('clusterC', 'clusterB') does not link the edge of clusterC and clusterB?

**Comment by xflr6** [comment] 2020-04-24 07:52
Hi. AFAICT the generated DOT is correct as are the nodes, clusters, and edges, but the edges to/from clusters end in the cluster's center point instead of at their rectangle boundary.

At https://www.graphviz.org/gallery/, there is a note on [fdpclust.htm](https://graphviz.gitlab.io/_pages/Gallery/undirected/fdpclust.html) (apart from note placement, it seems to be rendered the same as in the [docs of this package](https://graphviz.readthedocs.io/en/stable/examples.html#fdpclust-py)):

> ``fdp`` is being actively worked on, so the probability of hitting a bug is higher than with neato.
> Also the quality of the layouts will be improving. 

I think this might be a bug in the underlying Graphiz that can be reported [upstream](https://gitlab.com/graphviz/graphviz/issues) (the issue tracker here is only for iussues in the Python `graphviz` wrapper).

Final note that I cannot reproduce this with `` graphviz version 2.38.0 (20140413.2041)`` or ``graphviz version 2.40.1 (20161225.0304)`` (the [fdpclust.py example](https://graphviz.readthedocs.io/en/stable/examples.html#fdpclust-py) in the docs was rendered with the former). Can you check which version or Graphviz (https://www.graphviz.org) you have installed (``dot -V``)?

**Comment by Rubiscooo** [comment] 2020-04-24 10:05
Oh,it turns out to be the case that my Graphviz version is old. My version is `graphviz version 2.28.0 (20110507.0327)` .
Use `graphviz version 2.38.0 (20140413.2041)` is OK.
Thanks so much!

**Comment by xflr6** [comment] 2020-04-24 10:06
Happy to help, closing.

**Closed by xflr6** 2020-04-24 10:06 UTC
