### ISSUE TITLE
Strange behaviour when adding a string with ":" as node identifier while creating a new edge

### ISSUE THREAD

**Issue by LucaGebhardt2206** [xflr6/graphviz#83] opened 2019-09-27 15:40 UTC
`diagram = Digraph()`
`diagram.node(account["id"], browser["id"])`
Creates a new node with the desired identifier: 01.08.2017-00:00:00

`diagram = Digraph()`
`diagram.edge(account["id"], browser["id"])`
 Unfortunately, it cuts of the identifier at the first ':': 01.08.2017-00

As a result, two different nodes are created.

I found in `lang.py` at line 81 that ":"  is used as a static identifier.
Probably, a variable identifier with ":" as default parameter would be an appropriate solution.

The debugger indicates that the string is assembled incorrectly: `'01.08.2017-00":00:00"' `

**Comment by xflr6** [comment] 2019-09-28 08:32
Thanks, AFAIU this is a duplicate of #53 (current workaround would be to not use node names with literal colons).

**Comment by xflr6** [comment] 2019-09-28 08:32
Duplicare of #53

**Closed by xflr6** 2019-09-28 08:32 UTC
