### ISSUE TITLE
AttributeError with Source.pipe(encoding)

### ISSUE THREAD

**Issue by Geo-Nik** [xflr6/graphviz#189] opened 2023-01-30 16:00 UTC
Hello, 
I got a similar error in Windows 10, Python 3.7, graphviz 2.83:
```.
WARNING    Traceback (most recent call last):
File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\...\hldsldcreator.py", line 427, in 
self.dlg.pushButton_2.clicked.connect(lambda: main(self))
File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\...\hldsldcreator.py", line 533, in main
gv2svg(file_path, svg_path_output)
File "C:/Users/.../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\...\hldsldcreator.py", line 451, in gv2svg
svg_file = gv_file.pipe(encoding='utf-8')
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\piping.py", line 110, in pipe 
encoding=encoding)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\_tools.py", line 171, in wrapper
return func(*args, **kwargs)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\piping.py", line 127, in _pipe_legacy
encoding=encoding)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\piping.py", line 149, in _pipe_future
return self._pipe_lines_string(*args, encoding=encoding, **kwargs)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\backend\piping.py", line 212, in pipe_lines_string
proc = execute.run_check(cmd, capture_output=True, quiet=quiet, **kwargs)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\backend\execute.py", line 88, in run_check
_write_stderr(proc.stderr)
File "C:\Users\...\AppData\Roaming\Python\Python37\site-packages\graphviz\backend\execute.py", line 116, in _write_stderr
sys.stderr.write(stderr)
AttributeError: 'NoneType' object has no attribute 'write'
```

In Ubuntu, everything works correctly (Python 3.8).
My code:
```
def gv2svg(input_file_path, output_file_path):
    gv_file = graphviz.Source.from_file(input_file_path, format='svg')
    
    svg_file = gv_file.pipe(encoding='utf-8')

    with open(output_file_path, 'w') as f:
        f.write(svg_file)
```

Do you have any ideas about what I have done wrong?

BR,
Volodymyr

**Comment by xflr6** [comment] 2023-01-30 18:43
Hi, I think you are looking for https://graphviz.readthedocs.io/en/stable/manual.html#existing-files ([`graphviz.render()`](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.render)).

```python
import pathlib

import graphviz

path = pathlib.Path('hello.gv')
path.write_text('graph { spam }')

graphviz.render('dot', 'svg', path)
```

> Do you have any ideas about what I have done wrong?

I cannot reproduce.

```python
...

src = graphviz.Source.from_file(path, format='svg')
svg = src.pipe(encoding='utf-8')

assert svg.startswith('<?xml ')
```

Does it work when you use `dot` on the command line with the same file?

**Comment by xflr6** [comment] 2023-01-30 19:10
Should be covered by test added in dfc7e187a2e0f44e291104a6933fba4c4d8b92f2: https://github.com/xflr6/graphviz/actions/runs/4047234921 passed.

**Comment by Geo-Nik** [comment] 2023-01-31 09:34
Hello, thank you.
> I think you are looking for https://graphviz.readthedocs.io/en/stable/manual.html#existing-files ([graphviz.render()](https://graphviz.readthedocs.io/en/stable/api.html#graphviz.render)).

I just looking for the method of how to open gv file and save it to SVG (or convert gv to SVG) using python.
Is there another solution for that?

> Does it work when you use dot on the command line with the same file?

Via the command line, everything works correctly.

**Comment by xflr6** [comment] 2023-02-05 09:15
Thanks for the update, closing.

**Closed by xflr6** 2023-02-05 09:15 UTC
