### ISSUE TITLE
0.20: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [xflr6/graphviz#177] opened 2022-07-04 09:58 UTC
Looks like with latest sphinx 5.0.2 it is not possible to generate documentation
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/graphviz-0.20/docs/conf.py", line 194, in <module>
    from sphinx.ext.autodoc import ClassLevelDocumenter, InstanceAttributeDocumenter
ImportError: cannot import name 'InstanceAttributeDocumenter' from 'sphinx.ext.autodoc' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/graphviz-0.20/docs/conf.py", line 194, in <module>
    from sphinx.ext.autodoc import ClassLevelDocumenter, InstanceAttributeDocumenter
ImportError: cannot import name 'InstanceAttributeDocumenter' from 'sphinx.ext.autodoc' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/graphviz-0.20/docs/conf.py", line 194, in <module>
    from sphinx.ext.autodoc import ClassLevelDocumenter, InstanceAttributeDocumenter
ImportError: cannot import name 'InstanceAttributeDocumenter' from 'sphinx.ext.autodoc' (/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py)
```

**Comment by xflr6** [comment] 2022-07-05 14:45
See also 61c42e177f1a6ca9a74bdda2da9ae0dcac06e74b.

**Comment by xflr6** [comment] 2022-07-23 11:40
Fixed in  [0.20.1 release](https://pypi.org/project/graphviz/#files) (1a9ebd130c029677aff37fd9d8733f4685a7d9a9)

**Closed by xflr6** 2022-07-23 11:40 UTC

**Comment by kloczek** [comment] 2022-07-23 14:01
Tested. It works now 👍 
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2
making output directory... done
[autosummary] generating autosummary for: _links.rst, api.rst, attributes.rst, basic_usage.rst, changelog.rst, custom_dot.rst, development.rst, engines.rst, escapes.rst, examples.rst, ..., neato_no_op.rst, node_ports.rst, notebooks.rst, piped_output.rst, quoting.rst, raw_dot.rst, release_process.rst, styling.rst, subgraphs_and_clusters.rst, unflatten.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 28 added, 0 changed, 0 removed
reading sources... [100%] unflatten
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-graphviz.3 { manual examples notebooks api changelog license development release_process } done
build succeeded.

The manual pages are in build/sphinx/man.
```

Two small issiues:
- in last version from conf.py has been removed man_page entry. I'm using it. Is it possible to restore it?
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -78,6 +78,16 @@
 # so a file named "default.css" will overwrite the builtin "default.css".
 html_static_path = ['_static']

+# -- Options for man pageoutput ----------------------------------------------
+man_pages = [
+    (
+        "index",
+        "graphviz",
+        "graphviz Python Module Documentation",
+        author,
+        1,
+    )
+]

 # -- Extension configuration -------------------------------------------------
```
- I cannot find wheherd is hardcoded generate pytest verbose output. Even runnimg `pytest -ra -q` is not causing that  verbose output is disabled
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-graphviz-0.20.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-graphviz-0.20.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -q

README.rst::README.rst PASSED                                                                                                                                        [  0%]
docs/api.rst::api.rst PASSED                                                                                                                                         [  0%]
docs/attributes.rst::attributes.rst PASSED                                                                                                                           [  0%]
docs/basic_usage.rst::basic_usage.rst PASSED                                                                                                                         [  1%]

[.and so on.]
```

**Comment by xflr6** [comment] 2022-07-27 20:23
Thanks, confirmed manpage building works:

```shell
$ ./build-docs.py -n -T -b man docs docs/_build
run ['build-docs.py', '-n', '-T', '-b', 'man', 'docs', 'docs/_build']

sphinx.cmd.build.main(['-n', '-T', '-b', 'man', 'docs', 'docs/_build'])
Running Sphinx v5.0.2
loading pickled environment... done
[autosummary] generating autosummary for: _links.rst, api.rst, attributes.rst, basic_usage.rst, changelog.rst, custom_dot.rst, development.rst, engines.rst, escapes.rst, examples.rst, ..., neato_no_op.rst, node_ports.rst, notebooks.rst, piped_output.rst, quoting.rst, raw_dot.rst, release_process.rst, styling.rst, subgraphs_and_clusters.rst, unflatten.rst
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... graphviz.1 { manual examples notebooks api changelog license development release_process } done
build succeeded.

The manual pages are in docs\_build.

PASSED (returncode 0)
```

>in last version from conf.py has been removed man_page entry. I'm using it. Is it possible to restore it

I don't think `docs/conf.py` is part of the API. AFAIU, it's not needed any more with the last update of `sphinx`: Could you just hard-code that, or derive it in a different way?

> I cannot find wheherd is hardcoded generate pytest verbose output.
> Even runnimg pytest -ra -q is not causing that verbose output is disabled

I found this [stackoverflow](https://stackoverflow.com/questions/32444402/is-there-an-option-for-pytest-to-ignore-the-setup-cfg-file) and it looks like you can also provide a nonexisting filename:

```shell
$ run-tests.py -c SPAM -qq
run ['run-tests.py', '-c', 'SPAM', '-qq']
pytest.main(['-c', 'SPAM', '-qq'])
........................................................................ [ 22%]
........................................................................ [ 44%]
........................................................................ [ 66%]
...........................................x............................ [ 88%]
......................................                                   [100%]
```

Without the wrapper:

```shell
$ pytest -c SPAM -qq
........................................................................ [ 22%]
........................................................................ [ 44%]
........................................................................ [ 66%]
...........................................x............................ [ 88%]
......................................                                   [100%]
```

**Comment by kloczek** [comment] 2022-07-28 06:16
> Thanks, confirmed manpage building works:

I didn't say that it does not build. I sayd that there is no man_pages entry in conf.py which is causimg that page is without autor and proper description.
