### ISSUE TITLE
Colons can break quoting

### ISSUE THREAD

**Issue by talwrii** [xflr6/graphviz#102] opened 2020-07-22 10:52 UTC
Running this:
```
import graphviz

g = graphviz.Digraph("G")
g.edge(
    "a",
    "python:3.7@sha256:e8351629fe38c67486f92c818040f285e470faaaad6e15a46711fa7e380d7cdf",
)
print(str(g))
```

With graphviz `0.14.1` produces the following output

```
digraph G {
	a -> python:"3.7@sha256":e8351629fe38c67486f92c818040f285e470faaaad6e15a46711fa7e380d7cdf
}
``` 

I don't think this is quoted correctly.

**Comment by xflr6** [comment] 2020-07-22 19:05
Thanks for the report. I am assuming the result you expect is

`"python:3.7@sha256:e8351629fe38c67486f92c818040f285e470faaaad6e15a46711fa7e380d7cdf"`

(colons part of a quoted string with the node id).

We have the drawback that colons in node ids are currently not supported (due to how the support for node port and compass is implemented), so this [works as documented](https://graphviz.readthedocs.io/en/stable/manual.html#node-ports-compass). See #53 to track progress on lifting this (maybe adding support to use tuples to specify `(node_id, port)`, `(node_id,)` and so on).

Duplicate of #53

**Closed by xflr6** 2020-07-22 19:05 UTC
