### ISSUE TITLE
AttributeError: module 'graphviz._compat' has no attribute 'get_startupinfo'

### ISSUE THREAD

**Issue by yy-cc-20** [xflr6/graphviz#163] opened 2022-03-10 03:03 UTC
~\anaconda3\lib\site-packages\graphviz\backend\execute.py in run_check(cmd, input_lines, encoding, capture_output, quiet, **kwargs)
     75             assert kwargs.get('input') is None
     76             assert iter(input_lines) is input_lines
---> 77             if kwargs.pop('capture_output'):
     78                 kwargs['stdout'] = kwargs['stderr'] = subprocess.PIPE
     79             proc = _run_input_lines(cmd, input_lines, kwargs=kwargs)

AttributeError: module 'graphviz._compat' has no attribute 'get_startupinfo'

**Comment by xflr6** [comment] 2022-03-10 09:45
Can you provide a minimal reproducible example?

What platform and what version of `graphviz` are you using?

**Comment by xflr6** [comment] 2022-03-14 08:49
Closing (cannot reproduce).

**Closed by xflr6** 2022-03-14 08:49 UTC
